### ISSUE TITLE
The parser is not able to handle Having count

### ISSUE THREAD

**Issue by victorsantoss** [jehugaleahsa/SQLGeneration#20]
A simple query is not properly handled by the parser. 

Original Query | Output query
-------------------|------------------
SELECT 1 HAVING count(1) = 1 | SELECT 1 HAVING count(1)

This one is even better:

Original Query | Output query
-------------------|------------------
SELECT 1 AS field HAVING count(1) = 1 order by field | SELECT 1 AS field HAVING count(1)

This can be easily reproduced on Test Method: TestSelect_Having

**Comment by jehugaleahsa** [comment]
Hmm... I bet the same test would fail with WHERE too. Looks like there is a
bug in the grammar giving higher precidence to functions than comparisons.

**Comment by victorsantoss** [comment]
Well, I just did a test with the WHERE using a count inside that and it worked well.

SELECT 1 AS field where (select count(1)) = 1

**Comment by jehugaleahsa** [comment]
I have addressed this bug in the code. Your queries above have been added to the test suite. I have checked the code in and published a NuGet package with the fixes.

**Comment by jehugaleahsa** [comment]
By the way, thanks for checking out my project. This was a pet project I kind of fell in love with a few years back. Eventually, I plan on going back the grammer/parser I wrote for this and making it easier to generate code from it. As you can see right now, it isn't the most reliable or easy to use parser.

**Comment by victorsantoss** [comment]
Thanks for the correction and for sure your project helps me a lot.
I planned to use it few weeks ago and if something strange happens I'll tell you and try to fix it too.
